import styles from '@/styles/Home.module.css';
import { Inter } from '@next/font/google';
import CustomButton from 'components/buttons/CustomButton';
import Head from 'next/head';
import {
  Window, WindowContent, WindowHeader
} from 'react95';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <Window className={styles.window}>
            <WindowHeader >
              Codex Terminal
            </WindowHeader>
            <WindowContent>
              <div className={styles.windowContent}>
                <p className={styles.contentText}> Do you want to enter?</p>
                <CustomButton buttonText="Enter" href="/dashboard"></CustomButton>
              </div>
            </WindowContent>
          </Window>
        </div>
      </main>
    </>
  );
}
